import numpy as np

from RoboInfoGather.pomdp import *
from RoboInfoGather.MCTS_planner import Loc
from RoboInfoGather.observation_utils import *
from RoboInfoGather.map_utils import *
from RoboInfoGather.dsl import *

from RoboInfoGather.synthesis.synthesis import *

import copy

from matplotlib import pyplot as plt

import openai
from openai import OpenAI
f = open('/robodata/user_data/npatt/explore-eqa/RoboInfoGather/openaikey.txt', 'r')
openai_api_key = f.read().rstrip('\n')
f.close()

def gen_prog_from_nl(nl_question):
    # Call Synth
    synthesizer = Synthesizer(
        config_file_path="RoboInfoGather/synthesis/synthesis_config.yaml",
        example_file_path="RoboInfoGather/synthesis/examples.yaml",
        preamble_file_path="RoboInfoGather/synthesis/prompt_preamble.txt",
    )

    query = f"Given the question `{nl_question}`, please provide a valid python program. Do not include any explanation, however you may include any necessary sub clauses, or queries. Please respond with only python executable code"
    result = synthesizer.generate(query)
    new_prog = result.get_program_object()

    return new_prog


# Checks if a natural language answer (from LLM based on produced output of query execution)
# matches with the ground truth

# Scores from 1 to 5
def eval_similarity(question, nl_ans, text_answer):
    f = open('./RoboInfoGather/eval_similarity_pre_prompt.txt', 'r')
    pre_prompt = f.read()
    f.close()
    prompt = pre_prompt + f"Given the examples please evaluate the following similarity.\nQuestion: {question}\nUtterance 1: {text_answer}\nUtterance 2: {nl_ans}\n\nPlease respond with only the numerical score\nScore: "

    client = OpenAI(api_key=openai_api_key)
    response = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18",
        messages=[{"role": "user", "content": f"{prompt}"}],
        stream=False,
        temperature=0.0
    )

    str_score = response.choices[0].message.content

    return str_score


def get_int_from_str(val):
    prompt = f"Please return an integer corresponding to this string: {val}\nReturn only the value of the integer:\n"

    client = OpenAI(api_key=openai_api_key)
    response = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18",
        messages=[{"role": "user", "content": f"{prompt}"}],
        stream=False,
        temperature=0.0
    )

    int_val = int(response.choices[0].message.content)

    return int_val

def get_int_str_from_str(val):
    prompt = f"Please return an integer corresponding to this string: {val}\nReturn only the value of the integer, or None if there is no corresponding integer:\n"

    client = OpenAI(api_key=openai_api_key)
    response = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18",
        messages=[{"role": "user", "content": f"{prompt}"}],
        stream=False,
        temperature=0.0
    )

    int_val = response.choices[0].message.content

    return int_val


# Extract a natural language answer from the queries output
def get_nl_answer(query_exec_res, question, query_str, choices=None):
    f = open('./RoboInfoGather/nl_answer_pre_prompt.txt', 'r')
    pre_prompt = f.read()
    f.close()
    prompt = pre_prompt + f"Please answer the question:\n`{question}`\n\ngiven the symbolic information:\n{query_exec_res}.\n\nwhich was generated by executing the query:\n{query_str}.\n\nPlease, only answer the question without any extra explanation provided:\n"

    client = OpenAI(api_key=openai_api_key)
    response = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18",
        messages=[{"role": "user", "content": f"{prompt}"}],
        stream=False,
        temperature=0.0
    )

    nl_answer = response.choices[0].message.content

    # Condition return on choices if not none
    if choices != None:
        int_val_str = get_int_str_from_str(nl_answer)
        try:
            int_val = int(int_val_str)
            truth_val = True

        except Exception as e:
            truth_val = False

        if truth_val:
            nl_answer_int = get_int_from_str(nl_answer)

            int_choices = []
            for choice in choices:
                int_choices.append(get_int_from_str(choice))

            dists = []
            for val in int_choices:
                dists.append(abs(nl_answer_int - val))

            nl_answer = int_choices[np.argmin(dists)]
        else:
            prompt = f"Which of the following choices ({choices}) is most similar to `{nl_answer}`? Please return only the choice that is most similar:\n"

            client = OpenAI(api_key=openai_api_key)
            response = client.chat.completions.create(
                model="gpt-4o-mini-2024-07-18",
                messages=[{"role": "user", "content": f"{prompt}"}],
                stream=False,
                temperature=0.0
            )

            nl_answer = response.choices[0].message.content

    return nl_answer


def eval_similarity_from_choices(pred_answer, choices, true_answer):
    int_pred_answer = get_int_from_str(pred_answer)
    int_true_answer = get_int_from_str(true_answer)

    int_choices = []
    for choice in choices:
        int_choices.append(get_int_from_str(choice))

    dists = []
    for val in int_choices:
        dists.append(abs(int_true_answer - val))

    scores = np.zeros_like(dists)
    return_dists = np.copy(dists)

    for i in range(len(scores)):
        scores[np.argmax(dists)] = i + 1
        dists[np.argmax(dists)] = -1

    for i in range(len(scores)):
        if int_pred_answer == int_choices[i]:
            return scores[i], scores, return_dists, int_choices, int_pred_answer, int_true_answer

    return 1, scores, return_dists, int_choices, int_pred_answer, int_true_answer

def get_objects_and_features_helper(component):
    # Start with list and then unify
    if type(component) is Query:
        obj_feat = [(component.obj_tp, None, None)]
        obj_feat += get_objects_and_features_helper(component.where_clause)
        return obj_feat
    elif type(component) is WhereClause:
        if component.where_tp == "feature_enum":
            return [(component.obj_tp, component.enum_feature, "feature_enum")]

        elif component.where_tp == "feature_scalar":
            return [(component.obj_tp, component.scalar_feature, "feature_scalar")]

        elif component.where_tp == "max":
            return [(component.obj_tp, component.scalar_feature, "feature_scalar")]

        elif component.where_tp == "min":
            return [(component.obj_tp, component.scalar_feature, "feature_scalar")]

        elif component.where_tp == "spatial_rel":
            return [(component.obj_tp2, None, None)]

        elif component.where_tp == "and":
            obj_feat = get_objects_and_features_helper(component.sub_where_clause[0])
            obj_feat += get_objects_and_features_helper(component.sub_where_clause[1])
            return obj_feat

        elif component.where_tp == "or":
            obj_feat = get_objects_and_features_helper(component.sub_where_clause[0])
            obj_feat += get_objects_and_features_helper(component.sub_where_clause[1])
            return obj_feat

        elif component.where_tp == "not":
            obj_feat = get_objects_and_features_helper(component.sub_where_clause[0])
            return obj_feat

        elif component.where_tp == "true":
            return []
        else:
            return []

    elif type(component) is Map or type(component) is Count:
        return get_objects_and_features_helper(component.query)

    elif type(component) is Primitives:
        if component.prim_tp == 'real':
            return []
        elif component.prim_tp == "op":
            obj_feat = get_objects_and_features_helper(component.prim_tp)
            obj_feat += get_objects_and_features_helper(component.prim_tp2)
            return obj_feat

        else:
            return get_objects_and_features_helper(component.prim_tp)

    elif type(component) is GetNth or type(component) is Aggregator:
        return get_objects_and_features_helper(component.list)


def get_objects_and_features(query):
    # Start with list and then unify
    obj_feat_list = get_objects_and_features_helper(query)

    # Unify
    obj_feat_dict = {}
    for obj, feat, tp in obj_feat_list:
        if obj in obj_feat_dict:
            if feat not in obj_feat_dict[obj]:
                enc_feat = {'name': feat, 'tp': tp}
                obj_feat_dict[obj].append(enc_feat)
        else:
            enc_feat = {'name': feat, 'tp': tp}
            obj_feat_dict[obj] = [enc_feat]

    return obj_feat_dict

def gen_pomdp_from_query(query, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp=None, gen_inform_priors=None):
    # Recurse on cases where "query" is aggregator, map, primitives, getnth, or count
    if type(query) is Map:
        # Add map feature to where clause for feature extraction
        query_to_send = copy.deepcopy(query.query)
        if query.map_tp == 'feature_scalar':
            temp_where = WhereClause(where_tp=query.map_tp, obj_tp=query.obj_tp, scalar_feature=query.map_feature, is_temp=True)
        else:
            temp_where = WhereClause(where_tp=query.map_tp, obj_tp=query.obj_tp, enum_feature=query.map_feature, is_temp=True)
        temp_where_and = WhereClause(where_tp='and', obj_tp=query.obj_tp, sub_where_clause=[temp_where, query_to_send.where_clause], is_temp=True)
        query_to_send.where_clause = temp_where_and
        return gen_pomdp_from_query(query_to_send, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp, gen_inform_priors)
    if type(query) is Primitives:
        # Need to combine pomdps for both prim sides
        new_pomdp = gen_pomdp_from_query(query.prim, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp, gen_inform_priors)
        return gen_pomdp_from_query(query.prim2, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, new_pomdp, gen_inform_priors)
    if type(query) is GetNth:
        return gen_pomdp_from_query(query.list, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp, gen_inform_priors)
    if type(query) is Count:
        return gen_pomdp_from_query(query.query, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp, gen_inform_priors)
    if type(query) is Aggregator:
        return gen_pomdp_from_query(query.list, pos, yaw, trav_map_og_dim, trav_map_og_res, vol_origin, configs, prev_pomdp, gen_inform_priors)

    theta = yaw 
    robot_init_loc = Loc(pos[0], pos[1], theta)

    if prev_pomdp == None:
        # Search Query and get object type list
        # (obj_tp, num, thresh, [relevant_features], priors)
        threshold = query.threshold
        num = query.limit

        obj_feat_dict = get_objects_and_features(query)

        # Make list
        obj_tp_list = []
        for obj in obj_feat_dict:
            obj_tp_list.append((obj, num, threshold, obj_feat_dict[obj], None))

        if gen_inform_priors != None:
            assert False # PRIORS?
        else:
            new_pomdp = POMDP(query, robot_init_loc, obj_tp_list, trav_map_og_dim, trav_map_og_res, vol_origin, configs)

        return new_pomdp
    else:
        assert False # Don't worry about this case now
